import fs from "node:fs";
import PDFDocument from "pdfkit";
import type { ActivityReportRow } from "./superadmin.repository";

interface ActivityReportPdfInput {
  generatedAtIso: string;
  generatedBy: string;
  filters: {
    range: "today" | "last7" | "thisMonth" | "custom";
    from: string;
    to: string;
    adminLabel: string;
  };
  rows: ActivityReportRow[];
}

const FONT_CANDIDATES = [
  "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
  "/usr/share/fonts/dejavu/DejaVuSans.ttf",
  "/System/Library/Fonts/Supplemental/Arial Unicode.ttf",
  "/System/Library/Fonts/Supplemental/Arial.ttf",
];

type PdfCell = {
  text: string;
  width: number;
};

export class ActivityReportPdfService {
  async render(input: ActivityReportPdfInput): Promise<Buffer> {
    const doc = new PDFDocument({
      autoFirstPage: true,
      margin: 36,
      size: "A4",
      info: {
        Title: "TTPU PMS - Admin Activity Audit Report",
      },
    });
    const chunks: Buffer[] = [];
    doc.on("data", (chunk) => chunks.push(Buffer.from(chunk)));
    const endPromise = new Promise<Buffer>((resolve, reject) => {
      doc.on("end", () => resolve(Buffer.concat(chunks)));
      doc.on("error", reject);
    });

    const fontPath = FONT_CANDIDATES.find((candidate) => fs.existsSync(candidate));
    if (fontPath) {
      doc.registerFont("activity-report-base", fontPath);
      doc.font("activity-report-base");
    }

    doc.fontSize(16).text("TTPU PMS - Admin Activity Audit Report", { align: "left" });
    doc.moveDown(0.3);
    doc.fontSize(10).text(`Generated at: ${input.generatedAtIso}`);
    doc.text(`Generated by: ${input.generatedBy}`);
    doc.moveDown(0.4);
    doc.text(
      `Filters: range=${input.filters.range}; from=${input.filters.from}; to=${input.filters.to}; admin=${input.filters.adminLabel}`,
    );
    doc.moveDown(0.8);

    const tableStartY = doc.y;
    const left = doc.page.margins.left;
    const usableWidth = doc.page.width - doc.page.margins.left - doc.page.margins.right;
    const columns: PdfCell[] = [
      { text: "Time", width: 78 },
      { text: "Admin", width: 108 },
      { text: "Action", width: 98 },
      { text: "Entity", width: 88 },
      { text: "Details", width: usableWidth - (78 + 108 + 98 + 88) },
    ];

    const drawHeader = (): number => {
      let x = left;
      const y = doc.y;
      doc.fontSize(10);
      for (const column of columns) {
        doc.rect(x, y, column.width, 20).stroke();
        doc.text(column.text, x + 4, y + 6, {
          width: column.width - 8,
          align: "left",
        });
        x += column.width;
      }
      return y + 20;
    };

    const rowToCells = (row: ActivityReportRow): PdfCell[] => [
      { text: row.time, width: columns[0].width },
      {
        text: `${row.admin_name ?? "System"}\n${row.admin_email ?? "-"}`,
        width: columns[1].width,
      },
      { text: row.action_type, width: columns[2].width },
      {
        text: `${row.entity_type ?? "-"}\n${row.entity_label}`,
        width: columns[3].width,
      },
      { text: row.details || "-", width: columns[4].width },
    ];

    const pageBottom = () => doc.page.height - doc.page.margins.bottom;
    const ensureRoom = (rowHeight: number): void => {
      if (doc.y + rowHeight <= pageBottom()) {
        return;
      }
      doc.addPage();
      drawHeader();
      doc.y += 20;
    };

    doc.y = tableStartY;
    drawHeader();
    doc.y += 20;

    for (const row of input.rows) {
      const cells = rowToCells(row);
      const rowHeight = Math.max(
        24,
        ...cells.map((cell) =>
          Math.ceil(
            doc.heightOfString(cell.text, {
              width: cell.width - 8,
              align: "left",
            }) + 8,
          ),
        ),
      );
      ensureRoom(rowHeight);
      let x = left;
      const y = doc.y;
      for (const cell of cells) {
        doc.rect(x, y, cell.width, rowHeight).stroke();
        doc.text(cell.text, x + 4, y + 4, {
          width: cell.width - 8,
          align: "left",
        });
        x += cell.width;
      }
      doc.y = y + rowHeight;
    }

    if (input.rows.length === 0) {
      doc.moveDown(0.5);
      doc.fontSize(11).text("No activity rows found for selected filters.");
    }

    doc.end();
    return endPromise;
  }
}

export function buildActivityPdfFilename(generatedAt: Date): string {
  const yyyy = generatedAt.getUTCFullYear();
  const mm = String(generatedAt.getUTCMonth() + 1).padStart(2, "0");
  const dd = String(generatedAt.getUTCDate()).padStart(2, "0");
  return `admin-activity-audit-${yyyy}${mm}${dd}.pdf`;
}

export function normalizeDisplayDateTime(inputIso: string): string {
  const date = new Date(inputIso);
  if (Number.isNaN(date.getTime())) {
    return inputIso;
  }
  return date.toISOString().replace("T", " ").replace("Z", " UTC");
}
